version: '3.7'

services:
    api:
        depends_on:
            - database
            - agenda_db
        build:
            context: .
            target: development
        container_name: rb_api
        command: yarn dev
        ports:
            - '1236:8080'
        volumes:
            - .:/home/node/app
            - api_node_modules:/home/node/app/node_modules

    database:
        image: postgres:latest
        container_name: rb_database
        restart: always
        ports:
            - '1237:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=resorption_bidonvilles
            - POSTGRES_PASSWORD=resorption_bidonvilles

    agenda_db:
        image: mongo:latest
        container_name: rb_agenda_db
        restart: always
        volumes:
            - ./agenda-data:/data/db
        ports:
            - '27017-27019:27017-27019'
        environment:
            MONGO_INITDB_ROOT_USERNAME: rbadmin
            MONGO_INITDB_ROOT_PASSWORD: rbadmin

    rb_agendash:
        depends_on:
          - agenda_db
        image: agenda/agendash
        container_name: rb_agendash
        environment:
            - COLLECTION=agendaJobs
            - MONGODB_URI=mongodb://rbadmin:rbadmin@agenda_db
        ports:
          - '3000:3000'
        restart: always

volumes:
    api_node_modules: