version: '3.7'

services:
    api:
        depends_on:
            - database
            - agenda_db
        build:
            context: .
            target: development
        container_name: rb_api
        command: ./wait-for-it.sh agenda_db:27017 -- yarn dev
        ports:
            - '1236:8080'
        volumes:
            - .:/home/node/app
            - api_node_modules:/home/node/app/node_modules

    database:
        image: postgres:latest
        container_name: rb_database
        restart: always
        ports:
            - '1237:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=resorption_bidonvilles
            - POSTGRES_PASSWORD=resorption_bidonvilles

    agenda_db:
        image: mongo:latest
        container_name: rb_agenda_db
        restart: always
        volumes:
            - ./agenda-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: demo

volumes:
    api_node_modules: