module.exports = {
    up: queryInterface => queryInterface.sequelize.query(
        'SELECT users.user_id AS id FROM users WHERE email = \'robot@action-bidonvilles.beta.gouv.fr\'',
        {
            type: queryInterface.sequelize.QueryTypes.SELECT,
        },
    ).then(([{ id }]) => queryInterface.bulkInsert(
        'ngos',
        [
            { name: '2ChosesLune' },
            { name: 'ACINA' },
            { name: 'ADAPGV' },
            { name: 'ADDAP 13' },
            { name: 'ADEFO' },
            { name: 'ADVSEA 84' },
            { name: 'AFEJI' },
            { name: 'ALFA3A' },
            { name: 'ALPIL' },
            { name: 'Alteralia' },
            { name: 'Amitiés Tsiganes' },
            { name: 'AMPIL' },
            { name: 'API Provence' },
            { name: 'AREA' },
            { name: 'AREAS' },
            { name: 'ASBL (Association Saint-Benoît-Labre)' },
            { name: 'Association des Cités du Secours Catholique (ACSC)' },
            { name: 'AUDACIA' },
            { name: 'CATHS/ARTAG Cabinet d\'étude' },
            { name: 'CCAS Charleville-Mézières' },
            { name: 'Cimade 34' },
            { name: 'Cité Myriam' },
            { name: 'COALLIA' },
            { name: 'Convivances' },
            { name: 'COS Quancard' },
            { name: 'Croix Rouge Française' },
            { name: 'Entraide Protestante' },
            { name: 'Entraides et Solidarités' },
            { name: 'Entreprendre pour Humaniser la Dépendance (Habitat et Humanisme)' },
            { name: 'Forum Réfugiés' },
            { name: 'France Horizon' },
            { name: 'HAS - L\'Habitat Social Alternatif' },
            { name: 'Horizon Amitié' },
            { name: 'La Rose des Vents' },
            { name: 'La Sauvegarde du Nord' },
            { name: 'Le Rocheton' },
            { name: 'Les Enfants du Canal' },
            { name: 'Les Forges' },
            { name: 'Médecins du Monde' },
            { name: 'Métropole de Grenoble ' },
            { name: 'Paroles vives' },
            { name: 'Première Urgence Internationale' },
            { name: 'Réseau ROMA' },
            { name: 'Romespérance' },
            { name: 'Roms Action' },
            { name: 'Solidarité Aire Toulonnaise (SAT)' },
            { name: 'SOLIHA' },
            { name: 'Trajectoires' },
            { name: 'Une Famille Un Toit (UFUT)' },
            { name: 'Unis Cité Toulouse' },
            { name: 'Ville de Strasbourg' },
        ].map(operator => Object.assign({}, operator, {
            created_by: id,
            updated_by: id,
        })),
    )),

    down: queryInterface => queryInterface.bulkDelete('ngos'),
};
