name: manual_release

on:
  workflow_dispatch:
    inputs:
      branch:
        default: 'master'
        description: 'Branch to checkout (master, issue/x)'
      tag:
        description: 'Docker tag'
        default: 'dev'

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: resorptionbidonvilles/api:latest,resorptionbidonvilles/api:${{ github.event.inputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}