name: qa

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Nom du tag à poser sur l''image Docker. Ce tag sera par ailleurs préfixé de `qa-`'
        required: true
        default: latest

jobs:
  build-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: resorptionbidonvilles/api:qa-${{ github.event.inputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
